### ISSUE TITLE
A few suggestions for the client side

### ISSUE THREAD

**Issue by sap7772000zilla** [lentschi/expiry_sync#1]
Hello.
Please consider the following:
- **Expiry notifications**: if I touch the notification AND the soon-to-expire(STE) items are not in the Default area that opens by default  then it looks as if the notification disappeared - that was really confusing the first few times - plus there is now way you can see the list afterwards unless you know where to look for. 
Suggestion1: please provide a distinct view that consolidates all expired or STE + individual location that can be accessed at any times. **_Better_**, in this view provide a filter that can allow displaying not only the items expired today but also those that will expire in X days/weeks/months.
- Search capabilities: 
1. **items**: is narrowed down to the storage displayed which drastically limits the results. Searching for the same item through each and every storage area is...painful / terrible / horrible. 
Suggestion2: provide an alternative to search in ALL storage as well as local/selected storage only
2. **string**: now only applies to description
Suggestion3: please consider full text indexing;
- **T-X%**: is not always possible to consume in one day canned beans with whip cream with salami and fresh pineapple...
Suggestion4: please consider generating a dummy expiry date earlier than the original to provide the user some buffer time for consumption: the user should select the X% and the app should automatically change the expiry date using the formula T(original date)- X%.
For example if expiry date is 2 months and X is 10 then the calculated expiry will be
60 - 6(=10% of 60) = 54 days -> this will be adopted by the system.
The color coding is an excellent idea to make the difference between the really expired items to the STE ones, the above dummies should also be listed together with the real ones
Thank you.

**Comment by lentschi** [comment]
@sap7772000zilla
This issue actually consists of many issues ;-) So I took the liberty of splitting them up (s. above references). If I forgot something, feel free to comment there!
