### ISSUE TITLE
Date Format

### ISSUE THREAD

**Issue by RicXXX** [lentschi/expiry_sync#10]
it should be nice to have the possibility to change the date format from MM/DD/YYYY to DD/MM/YYYY.
Thanks

**Comment by lentschi** [comment]
@RicXXX 
> it should be nice to have the possibility to change the date format from MM/DD/YYYY to DD/MM/YYYY.

That is related to #4:
If you change the language from within settings and then restart the app, the date format will also change accordingly.
(So for example, if the Italian language was added, the date format should be exactly what you suggested.)

**Comment by RicXXX** [comment]
Italian language added, so data format is as requested.
Thanks
Ric
