### ISSUE TITLE
Impossible to log in

### ISSUE THREAD

**Issue by RicXXX** [lentschi/expiry_sync#9]
Since 20 September 2018, log in (to sync with the server) does not work.
![img1](https://user-images.githubusercontent.com/43966625/46623590-5af8f780-cb2e-11e8-8348-8bd7602077f9.jpg)

I've tried also to change the password for my account, but I received an error message from the server, 
![img2](https://user-images.githubusercontent.com/43966625/46623442-efaf2580-cb2d-11e8-9577-652813129a35.jpg)
it looks like the server is down.

Thanks for any support.
Regards
Ric

**Comment by lentschi** [comment]
@RicXXX 

I talked to the maintainer of the 'Advanced' server and he said due to recurring problems with his db server he had to switch servers.

According to him now everything should be back to working.

Cheers, Flo

**Comment by RicXXX** [comment]
Thanks
Server looks OK
